import Header from "@/components/Header";
import "@/styles/globals.scss";
// Types
import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
    title: "Next 13 whatsApp",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
